--- 
- hosts: localhost
  vars:
    state: present
    s3_bucket: jenkyterraformjawnt
    key: terraform.tfstate
    region: us-east-1
    app-env: dev 
  tasks:
  - name: runs terraform scripts
    terraform:
      project_path: "./"
      state: present
      backend_config:
          bucket: "{{ s3_bucket }}"
          key: "{{ key }}"
          region: "{{ region }}"
      variables_file: "{{ app_env }}.tfvars"
      workspace: "{{ app_env }}"
       