--- 
- name: Provisioning aws resources with this playbook
  hosts: localhost
  #remote_user: ansadmin
  #gather_facts: true 
  become: false 

  tasks:
  - name: Install boto3
    pip:
      name: boto3
      state: present
    become: true   

  - name: Create s3 bucket
    s3_bucket:
      name: jenkyterraformjawnt
      state: present